//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cocktails07.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CockTail
    {
        public CockTail()
        {
            this.CocktailCordials = new HashSet<CocktailCordial>();
            this.CocktailLiquors = new HashSet<CocktailLiquor>();
            this.CocktailNoAlcohols = new HashSet<CocktailNoAlcohol>();
            this.Garnishes = new HashSet<Garnish>();
            this.Processes = new HashSet<Process>();
        }
    
        public long CocktailId { get; set; }
        public Nullable<long> GlassId { get; set; }
        public string Name { get; set; }
        public Nullable<long> CategoryId { get; set; }
    
        public virtual Glass Glass { get; set; }
        public virtual ICollection<CocktailCordial> CocktailCordials { get; set; }
        public virtual ICollection<CocktailLiquor> CocktailLiquors { get; set; }
        public virtual ICollection<CocktailNoAlcohol> CocktailNoAlcohols { get; set; }
        public virtual ICollection<Garnish> Garnishes { get; set; }
        public virtual ICollection<Process> Processes { get; set; }
        public virtual Category Category { get; set; }
    }
}
