//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cocktails07.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CockTailsIngredientsEntities : DbContext
    {
        public CockTailsIngredientsEntities()
            : base("name=CockTailsIngredientsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CockTail> CockTails { get; set; }
        public DbSet<CocktailCordial> CocktailCordials { get; set; }
        public DbSet<CocktailLiquor> CocktailLiquors { get; set; }
        public DbSet<CocktailNoAlcohol> CocktailNoAlcohols { get; set; }
        public DbSet<Cordial> Cordials { get; set; }
        public DbSet<Garnish> Garnishes { get; set; }
        public DbSet<Glass> Glasses { get; set; }
        public DbSet<Liquor> Liquors { get; set; }
        public DbSet<NoAlcohol> NoAlcohols { get; set; }
        public DbSet<Process> Processes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<UserUsage> UserUsages { get; set; }
        public DbSet<Category> Categories { get; set; }
    }
}
